name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: ":beetle: Fixes"
    label: "fix"
  - title: ":rocket: Features"
    label: "feature"
  - title: ":books: Documentation"
    label: "docs"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":hammer: Refactoring"
    label: "refactor"
  - title: ":racehorse: Performance"
    label: "perf"
  - title: ":rotating_light: Testing"
    label: "test"
  - title: ":package: Build System"
    label: "build"
  - title: ":construction_worker: Continuous Integration"
    label: "ci"
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":robot: Dependency Updates"
    label: "dependencies"

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "maintenance"
      - "docs"
      - "dependencies"
      - "security"
  default: patch
