name: Codecov

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root -vvv

      - name: Run nox
      - run: nox --sessions coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
