name: Codecov
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: x64
    - run: python -m pip install --upgrade pip
    - run: python -m pip install nox
    - run: python -m pip install poetry
    - run: nox --sessions tests-3.8 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
