name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64
      - run: python -m pip install --upgrade pip
      - run: python -m pip install nox
      - run: python -m pip install poetry
      - run: nox
      - run: poetry build
      - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
