name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    name: Python
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -m pip install --upgrade pip
      - run: python -m pip install nox
      - run: python -m pip install poetry
      - run: nox
